Iteration 1 review
Stuysha/practicum-android-diploma pull request #38
Opened 2024-04-02 10:07 UTC by Stuysha

1. https://github.com/users/Stuysha/projects/1/views/1
Список выполненных задач:
-Создать иконку приложения
-Настройка Network Client (Retrofit) в Data слое
-Добавить иконки и шрифты на основе дизайна из Figma
-Добавить функцию debounce, Data-слоя
-Добавить файлы build.gradle и AndroidManifest.xml, создать базовый набор пакетов data, domain, ui, presentation
-Настройка Dependency Injection (Koin)
-Добавить темы и цвета на основе дизайна из Figma
-Добавить граф навигацию
-Добавить в граф пустые фрагменты для экранов поиска, фильтрации, вакансии, команды.
-Настройка базы данных room в Data слое
-Добавить функцию проверки наличия интернета, Data-слоя
-Реализовать экран Команда
Первоначальная оценка времени выполнения задач - 6 дней
Реальное время, потраченное на решении каждой задачи- 5 дней

2024-04-03 18:45 UTC, DmitrijEgorow requested changes

2024-04-03 18:45 UTC, DmitrijEgorow commented on app/src/main/AndroidManifest.xml
> +        android:required="false" />
Зачем?

2024-04-03 18:45 UTC, DmitrijEgorow commented on app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.CALL_PHONE"/>
Protection level: dangerous permission
Точно требуется это разрешение?

2024-04-03 18:45 UTC, DmitrijEgorow commented on app/src/main/java/ru/practicum/android/diploma/ui/root/RootActivity.kt
> +    private val binding get() = _binding!!
Зачем два байдинга в активности?

2024-04-03 18:45 UTC, DmitrijEgorow commented on app/src/main/res/layout/fragment_team.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
Code -> Reformat Code

2024-04-03 18:45 UTC, DmitrijEgorow commented on app/src/main/res/layout/fragment_team.xml
> +        android:layout_marginEnd="8dp"
Нужно вынести в dimens

2024-04-03 18:45 UTC, DmitrijEgorow commented on app/src/main/res/values-night/themes.xml
В тёмной теме некорректный цвет нижнего меню


![Screenshot_20240403_211600](https://github.com/Stuysha/practicum-android-diploma/assets/36837067/bc03c03c-64ca-4fad-9086-581e395dc15e)

2024-04-04 04:32 UTC, nim0y commented on app/src/main/java/ru/practicum/android/diploma/ui/root/RootActivity.kt
> +    private val binding get() = _binding!!
Для обеспечения безопасности и удобства работы с библиотекой View Binding в Android.

_binding является приватной переменной, которая может быть null. Это позволяет избежать NullPointerException, так как вы можете безопасно обращаться к _binding без необходимости проверять его на null перед каждым использованием.
binding является свойством, которое предоставляет безопасный доступ к _binding. Оно использует оператор !!, который гарантирует, что _binding не null в момент доступа. Если _binding будет null, приложение выбросит исключение NullPointerException, что помогает обнаружить ошибки в коде.
Этот подход позволяет избежать потенциальных ошибок, связанных с использованием null значений, и делает код более читаемым и безопасным. Вместо того чтобы каждый раз проверять _binding на null, вы можете просто использовать binding, что делает код более чистым и понятным.

2024-04-04 12:58 UTC, Stuysha commented on app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.CALL_PHONE"/>
Не требуется, <uses-permission android:name="android.permission.CALL_PHONE"/>,  удаляю.

2024-04-04 13:44 UTC, merged